version: '2'
services:
  db:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo16@2024
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  app:
    image: odoo:16
    user: root
    depends_on:
      - db
    ports:
      - "10016:8069"
      - "20016:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo16@2024
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./ez_addons:/mnt/extra-addons2
      - ./etc:/etc/odoo
    restart: always             # run as a service
    networks:
      - default
      - odoo16-net
      
networks:
  default:
    driver: bridge
  odoo16-net:
    name: ors_network
    external: true

######################################
# git submodule init 
# git submodule update
#
######################################
# icon menu generator
# https://spilymp.github.io/ibo/
#
#
#